fix output form of blockcmp
HaechangLee/Project2 pull request #21
Opened 2024-05-09 14:57 UTC by ns0416

blockcmp 출력 폼을 변경하였습니다.
리뷰부탁드립니다.
감사합니다.

2024-05-09 15:46 UTC, HaechangLee requested changes
comment 확인 부탁드립니다

2024-05-09 15:46 UTC, HaechangLee commented on main.c
> +		printf("text1 is bigger\n");
끝에 개행문자 하나씩 더넣어주세요...ㅠㅠ

2024-05-09 15:46 UTC, HaechangLee commented on main.c
> +		printf("text2 is bigger\n");
끝에 개행문자 하나씩 더넣어주세요...ㅠㅠ

2024-05-09 15:46 UTC, HaechangLee commented on main.c
> +		printf("sizes are equal\n");
끝에 개행문자 하나씩 더넣어주세요...ㅠㅠ

2024-05-09 15:49 UTC, HaechangLee approved these changes
잘 구현하셨네요~

2024-05-09 15:50 UTC, JiNewPark approved these changes
good

2024-05-09 15:50 UTC, JaeSeungJae approved these changes
굿

2024-05-10 09:59 UTC, JungSungYeob approved these changes
잘 동작합니다.

2024-05-10 10:02 UTC, merged